#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    systemctl daemon-reload  > /dev/null 2>&1 || true
    systemctl enable mapping-touchscreen.service  > /dev/null 2>&1 || true
    systemctl start mapping-touchscreen.service > /dev/null 2>&1 || true
fi
exit 0