#!/bin/sh

set -e

systemctl stop mapping-touchscreen.service  > /dev/null 2>&1 || true
systemctl disable mapping-touchscreen.service > /dev/null 2>&1 || true
systemctl daemon-reload > /dev/null 2>&1 || true

exit 0